"""
Generate synthetic sample CT-like images for testing the pipeline
without requiring real patient data.

These are NOT real medical images. They are synthetic grayscale images
designed to exercise the segmentation model inference code path.
"""

import numpy as np
from pathlib import Path
from PIL import Image


def make_synthetic_ct_slice(
    size: int = 512,
    add_anomaly: bool = False,
    seed: int = 42,
) -> np.ndarray:
    """
    Generate a synthetic grayscale image that loosely mimics CT HU texture.
    Organs are represented as elliptical regions with different intensity bands.
    This is NOT anatomically accurate — it only exercises the inference pipeline.
    """
    rng = np.random.default_rng(seed)
    img = np.zeros((size, size), dtype=np.float32)

    # Background tissue noise
    img += rng.normal(0.15, 0.04, (size, size)).astype(np.float32)

    cx, cy = size // 2, size // 2

    def ellipse_mask(cx, cy, rx, ry):
        Y, X = np.ogrid[:size, :size]
        return ((X - cx) ** 2 / rx ** 2 + (Y - cy) ** 2 / ry ** 2) <= 1.0

    # Liver — right side, large
    liver = ellipse_mask(cx - 60, cy + 30, 110, 80)
    img[liver] = rng.normal(0.55, 0.03, img[liver].shape)

    # Spleen — left side
    spleen = ellipse_mask(cx + 90, cy + 20, 45, 55)
    img[spleen] = rng.normal(0.52, 0.03, img[spleen].shape)

    # Pancreas — center, small
    pancreas = ellipse_mask(cx + 10, cy - 10, 45, 20)
    img[pancreas] = rng.normal(0.45, 0.04, img[pancreas].shape)

    # Kidneys
    kidney_l = ellipse_mask(cx + 100, cy + 60, 30, 42)
    kidney_r = ellipse_mask(cx - 100, cy + 60, 30, 42)
    img[kidney_l] = rng.normal(0.40, 0.03, img[kidney_l].shape)
    img[kidney_r] = rng.normal(0.40, 0.03, img[kidney_r].shape)

    if add_anomaly:
        # Small mass on liver edge
        mass = ellipse_mask(cx - 120, cy + 50, 12, 10)
        img[mass] = rng.normal(0.72, 0.02, img[mass].shape)

    img = np.clip(img, 0, 1)
    return (img * 255).astype(np.uint8)


def save_sample_data(output_dir: Path = Path("data/sample_data")):
    output_dir.mkdir(parents=True, exist_ok=True)

    # Normal scan
    normal = make_synthetic_ct_slice(add_anomaly=False, seed=1)
    Image.fromarray(normal).convert("RGB").save(output_dir / "ct_normal_baseline.png")
    print(f"Saved: {output_dir / 'ct_normal_baseline.png'}")

    # Scan with synthetic anomaly
    abnormal = make_synthetic_ct_slice(add_anomaly=True, seed=2)
    Image.fromarray(abnormal).convert("RGB").save(output_dir / "ct_abdomen_slice.png")
    print(f"Saved: {output_dir / 'ct_abdomen_slice.png'}")

    # Write a fake clinical note
    (output_dir / "clinical_note_case1.txt").write_text(
        "58-year-old male. Elevated liver enzymes (ALT 2.4× ULN).
"
        "Abdominal discomfort for 3 weeks. No prior liver disease.
"
        "Referred for CT abdomen.
"
        "
"
        "NOTE: This is a synthetic clinical note for testing purposes only.
"
        "It does not represent a real patient."
    )
    print(f"Saved: {output_dir / 'clinical_note_case1.txt'}")

    # Write a README for the sample data folder
    (output_dir / "README.md").write_text(
        "# Sample Data

"
        "These files are **synthetically generated** for testing the inference pipeline.
"
        "They are NOT real medical images or patient data.

"
        "Generated by `data/generate_sample_data.py`.

"
        "| File | Description |
"
        "|---|---|
"
        "| `ct_normal_baseline.png` | Synthetic CT slice, no anomalies |
"
        "| `ct_abdomen_slice.png` | Synthetic CT slice with a small synthetic mass |
"
        "| `clinical_note_case1.txt` | Synthetic clinical history for case 1 |
"
    )
    print("Sample data generation complete.")


if __name__ == "__main__":
    save_sample_data()
